const {JSDOM} = require('jsdom');
const fs = require('fs');
const assert = require('node:assert/strict');
const code = fs.readFileSync(__dirname+'/web/console.js', 'utf8');
(async () => {
  const dom = new JSDOM(`<pre class="console-output"><span class="pipeline-new-node">[Pipeline] sh\n</span><span class="pipeline-node-1">Timeout set to expire in 16 min\n</span><span class="pipeline-node-2">Running on <a href="/worker">agent</a> in /workspace\n</span><span class="pipeline-node-3">ERROR: Helm failed\n</span><span class="pipeline-node-4">Cloning the remote Git repository\nERROR: checkout failed\n</span></pre>`, {url:'https://jenkins.example/job/aof-back-dev/5/console', runScripts:'outside-only'});
  dom.window.eval(code);
  dom.window.document.dispatchEvent(new dom.window.Event('DOMContentLoaded'));
  const d=dom.window.document, pre=d.querySelector('pre');
  assert(pre.classList.contains('aof-compact'));
  assert(d.querySelector('.pipeline-node-1').classList.contains('aof-routine'));
  assert(d.querySelector('.pipeline-node-2').classList.contains('aof-routine'));
  assert(!d.querySelector('.pipeline-node-3').classList.contains('aof-routine'));
  assert(!d.querySelector('.pipeline-node-4').classList.contains('aof-routine'));
  const appended=d.createElement('span'); appended.className='pipeline-node-5'; appended.textContent='Timeout set to expire in 2 min\n'; pre.append(appended);
  await new Promise(r=>setTimeout(r,0));
  assert(appended.classList.contains('aof-routine'));
  appended.append('ERROR: interrupted\n');
  await new Promise(r=>setTimeout(r,0));
  assert(!appended.classList.contains('aof-routine'));
  assert(!d.querySelector('input'));
  assert(!d.body.textContent.includes('Show Jenkins details'));
  assert(pre.classList.contains('aof-compact'));
  assert(d.querySelector('a').getAttribute('href')==='/worker');
  dom.window.close();
  const other = new JSDOM('<pre class="console-output">Other job</pre>', {url:'https://jenkins.example/job/aof-front/5/console',runScripts:'outside-only'});
  other.window.eval(code); other.window.document.dispatchEvent(new other.window.Event('DOMContentLoaded'));
  assert(!other.window.document.querySelector('input')); other.window.close();
  console.log('PASS: compact view, linked messages, error preservation, live updates, no details toggle, other-job isolation');
})();
